feat(ui): port Checkbox component
revoltchat/revoltchat-solid-client-monorepo pull request #80
Opened 2022-11-25 16:10 UTC by Supertigerr

## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

I have directly ported over the checkbox component from revite.

Issue: https://github.com/revoltchat/revoltchat-solid-client-monorepo/issues/74

2022-11-25 16:17 UTC, Rexogamer requested changes
Haven't tested/fully reviewed the code, but one minor point - `CheckBox.tsx` should be renamed to `Checkbox.tsx` as it's one word

2022-11-26 09:21 UTC, harshmangalam commented
Instead of destructure 
```ts
 const {
    disabled,
    title,
    description,
    value,
    onChange,
    ...otherProps
  } = props;
```

use provided utilities splitProps
```ts
const [local,others] = splitProps(
  props,
  ["disabled", "title", "description", "value", "onChange"]
);

```

 and then in jsx

```tsx

 <Base {...others}>

<Checkmark value={local.value} class="checkmark">
        <BiRegularCheck size={20} class="check" />
 </Checkmark>

```

2022-11-26 09:22 UTC, Supertigerr commented
Ah, I always forget about `splitProps`. Will make changes now thanks!

2022-11-26 09:57 UTC, harshmangalam commented
Use `<Show>` component to show conditional data .

```tsx
 <Show when={local.description}>
          <Description>{local.description}</Description>
 </Show>

```

2022-11-26 10:00 UTC, Supertigerr commented
I was thinking about changing that, but then I saw other components do it the old way, so I left it. I guess I'll change it. Thanks.

2022-11-30 11:32 UTC, insertish requested changes
Just want these two things cleaned up.

PS. currently busy with university, will be merging PRs tomorrow.

2022-11-30 11:32 UTC, insertish commented on components/ui/components/design/atoms/inputs/Checkbox.tsx
> +  //TODO: When value is checked, allow me to add .hover { .checkmark { border-color:  var(--tertiary-foreground);} }
This comment doesn't need to be included.
Note: may cause issues with goober, comments must be `/* */`.

2022-11-30 11:32 UTC, insertish commented on components/ui/components/design/atoms/inputs/Checkbox.tsx
> +                        </TitleAction>*/}
This can also be ignored for now. (this will make `TitleAction` unused too)

2022-12-01 20:49 UTC, insertish approved these changes

2022-12-01 20:50 UTC, Rexogamer approved these changes

2022-12-01 20:51 UTC, merged